spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Education_System?characterEncoding=utf8&useSSL=false
    username: root
    #密码
    password: "0410"
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis xml保存路径
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.demo.entity

# 配置打印 MyBatis 执行的 SQL
logging:
  level:
    com:
      example:
        demo: debug
#验证码
imagepath: ./image/A